// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BrandLoadController from "./brand_load_controller"
application.register("brand-load", BrandLoadController)

import CityLoadController from "./city_load_controller"
application.register("city-load", CityLoadController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
