#databases:
#  - name: mysite
#    databaseName: mysite
#    user: mysite

services:
  - type: web
    name: app-city-guard
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
      - key: RAILS_MASTER_KEY
        sync: false